/**
 * AutomatiQA - Apache JMeter JMX Sanitizer & Validator
 * 
 * Ensures all generated and downloaded .jmx XML scripts strictly adhere to standard, native Apache JMeter 5.x/5.6.3
 * GUI component classes and XML specifications.
 * 
 * Fixes:
 * 1. Third-party plugin dependencies (e.g. kg.apc.*) that cause:
 *    'Cannot invoke "org.apache.jmeter.gui.JMeterGUIComponent.clearGui()" because "guicomp" is null'
 * 2. Malformed closing tags or XML pull parser syntax errors (e.g. `<responseData>false</-...`) that cause:
 *    'XmlPullParserException: expected name start and not -' / SampleSaveConfigurationConverter unmarshal ConversionException
 * 3. Incomplete, truncated, or corrupted <value class="SampleSaveConfiguration"> elements across ResultCollectors
 * 4. Unescaped XML entities (& in query strings, <, >, ", ')
 * 5. Stray text or unclosed comments outside XML tags
 */

export const CANONICAL_SAMPLE_SAVE_CONFIG = `            <value class="SampleSaveConfiguration">
              <time>true</time>
              <latency>true</latency>
              <timestamp>true</timestamp>
              <success>true</success>
              <label>true</label>
              <code>true</code>
              <message>true</message>
              <threadName>true</threadName>
              <dataType>true</dataType>
              <encoding>false</encoding>
              <assertions>true</assertions>
              <subresults>true</subresults>
              <responseData>false</responseData>
              <samplerData>false</samplerData>
              <xml>false</xml>
              <fieldNames>true</fieldNames>
              <responseHeaders>false</responseHeaders>
              <requestHeaders>false</requestHeaders>
              <responseDataOnError>false</responseDataOnError>
              <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>
              <assertionsResultsToSave>0</assertionsResultsToSave>
              <bytes>true</bytes>
              <sentBytes>true</sentBytes>
              <url>true</url>
              <threadCounts>true</threadCounts>
              <idleTime>true</idleTime>
              <connectTime>true</connectTime>
            </value>`;

export function sanitizeJmxScript(rawJmx: string): string {
  if (!rawJmx || typeof rawJmx !== 'string') return rawJmx;

  let cleaned = rawJmx.trim();

  // 1. Remove markdown code block wrappers (e.g. ```xml ... ``` or ``` ...)
  cleaned = cleaned.replace(/^```[a-zA-Z]*\s*/i, '').replace(/\s*```$/i, '').trim();

  // 2. Strip any JavaScript comments or truncation markers that could have been injected by storage helpers
  cleaned = cleaned.replace(/\/\/\s*\.\.\.\s*\[content preserved.*$/gim, '');
  cleaned = cleaned.replace(/\/\*[\s\S]*?\[content preserved[\s\S]*?\*\//gim, '');
  cleaned = cleaned.replace(/\/\/\s*Generated by.*$/gim, '');

  // 3. Remove XML comments to avoid any broken or unclosed comment markers interfering with XML parsing
  cleaned = cleaned.replace(/<!--[\s\S]*?-->/g, '');

  // 4. Strip any half-written open tag at the very end of a truncated string
  cleaned = cleaned.replace(/<[^>]*$/g, '').trim();

  // 5. Normalize and strictly validate all SampleSaveConfiguration blocks
  cleaned = cleaned.replace(
    /<value\s+class=["']SampleSaveConfiguration["']>[\s\S]*?(?:<\/value>(?:\s+[a-zA-Z0-9_.-]+)?|(?=<\/objProp>))/gi,
    CANONICAL_SAMPLE_SAVE_CONFIG.trim()
  );

  // If any objProp has saveConfig without value class
  cleaned = cleaned.replace(
    /<objProp>\s*<name>saveConfig<\/name>\s*<\/objProp>/gi,
    `<objProp>\n            <name>saveConfig</name>\n${CANONICAL_SAMPLE_SAVE_CONFIG}\n          </objProp>`
  );

  // 6. Fix any malformed closing tags containing hyphens, dashes, or broken names (e.g., </-responseData>, </-->, </- ...>)
  cleaned = cleaned.replace(/<\/\s*-\s*([a-zA-Z0-9_:]+)\s*>/g, '</$1>');
  cleaned = cleaned.replace(/<\/\s*-+[^>]*>/g, '');
  cleaned = cleaned.replace(/<\/\s*-+\s*/g, '');

  // 7. Replace all 3rd-party plugin visualizers (kg.apc.*) with standard native Apache JMeter 5.x visualizers
  // This eliminates the 'guicomp is null' error in standard JMeter installations
  cleaned = cleaned.replace(/guiclass=["']kg\.apc\.jmeter\.vizualizers\.HitsPerSecondGui["']/g, 'guiclass="RespTimeGraphVisualizer"');
  cleaned = cleaned.replace(/guiclass=["']kg\.apc\.jmeter\.vizualizers\.TransactionsPerSecondGui["']/g, 'guiclass="StatVisualizer"');
  cleaned = cleaned.replace(/guiclass=["']kg\.apc\.jmeter\.vizualizers\.ResponseTimesOverTimeGui["']/g, 'guiclass="RespTimeGraphVisualizer"');
  cleaned = cleaned.replace(/guiclass=["']kg\.apc\.jmeter\.vizualizers\.ThreadsStateOverTimeGui["']/g, 'guiclass="GraphVisualizer"');
  cleaned = cleaned.replace(/guiclass=["']kg\.apc\.jmeter\.vizualizers\.BytesThroughputOverTimeGui["']/g, 'guiclass="StatVisualizer"');
  cleaned = cleaned.replace(/guiclass=["']kg\.apc\.jmeter\.vizualizers\.LatenciesOverTimeGui["']/g, 'guiclass="RespTimeGraphVisualizer"');
  cleaned = cleaned.replace(/guiclass=["']kg\.apc\.[^"']+["']/g, 'guiclass="StatVisualizer"');

  // Replace 3rd-party plugin visualizer testclass with standard ResultCollector
  cleaned = cleaned.replace(/testclass=["']kg\.apc\.jmeter\.vizualizers\.CorrectedResultCollector["']/g, 'testclass="ResultCollector"');
  cleaned = cleaned.replace(/testclass=["']kg\.apc\.[^"']+["']/g, 'testclass="ResultCollector"');

  // Replace 3rd-party plugin thread groups (Ultimate/Stepping Thread Groups) with standard native ThreadGroup
  cleaned = cleaned.replace(/testclass=["']kg\.apc\.jmeter\.threads\.(Ultimate|Stepping)ThreadGroup["']/g, 'testclass="ThreadGroup"');
  cleaned = cleaned.replace(/guiclass=["']kg\.apc\.jmeter\.threads\.(Ultimate|Stepping)ThreadGroupGui["']/g, 'guiclass="ThreadGroupGui"');

  // Also replace any testname referencing jp@gc with native names
  cleaned = cleaned.replace(/testname=["']jp@gc\s*-\s*Hits per Second["']/g, 'testname="Response Time Graph"');
  cleaned = cleaned.replace(/testname=["']jp@gc\s*-\s*Transactions per Second["']/g, 'testname="Aggregate Report"');
  cleaned = cleaned.replace(/testname=["']jp@gc\s*-\s*Response Times Over Time["']/g, 'testname="Response Time Graph"');
  cleaned = cleaned.replace(/testname=["']Hits per Second["']/g, 'testname="Response Time Graph"');

  // Ensure HTTPSampler arguments have standard GUI classes and testclass
  cleaned = cleaned.replace(/<elementProp name="HTTPsampler\.Arguments" elementType="Arguments"(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    return match.replace('elementType="Arguments"', 'elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments"');
  });

  // 8. Fix common property typos from AI generation
  cleaned = cleaned.replace(/name=["']Asserion\.test_strings["']/g, 'name="Assertion.test_strings"');
  cleaned = cleaned.replace(/name=["']Asserion\.([a-zA-Z0-9_]+)["']/g, 'name="Assertion.$1"');

  // 9. Ensure standard GUI classes are properly attached to main elements if missing or empty
  cleaned = cleaned.replace(/<TestPlan(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<TestPlan', '<TestPlan guiclass="TestPlanGui" testclass="TestPlan"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<ThreadGroup(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<ThreadGroup', '<ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<HTTPSamplerProxy(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<HTTPSamplerProxy', '<HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<HeaderManager(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<HeaderManager', '<HeaderManager guiclass="HeaderPanel" testclass="HeaderManager"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<ResponseAssertion(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<ResponseAssertion', '<ResponseAssertion guiclass="AssertionGui" testclass="ResponseAssertion"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<DurationAssertion(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<DurationAssertion', '<DurationAssertion guiclass="DurationAssertionGui" testclass="DurationAssertion"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<ConstantTimer(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<ConstantTimer', '<ConstantTimer guiclass="ConstantTimerGui" testclass="ConstantTimer"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<CookieManager(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<CookieManager', '<CookieManager guiclass="CookiePanel" testclass="CookieManager"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<CacheManager(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<CacheManager', '<CacheManager guiclass="CacheManagerGui" testclass="CacheManager"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<ConfigTestElement(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<ConfigTestElement', '<ConfigTestElement guiclass="HttpDefaultsGui" testclass="ConfigTestElement"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<CSVDataSet(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<CSVDataSet', '<CSVDataSet guiclass="TestBeanGUI" testclass="CSVDataSet"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<RegexExtractor(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<RegexExtractor', '<RegexExtractor guiclass="RegexExtractorGui" testclass="RegexExtractor"');
    }
    return match;
  });

  cleaned = cleaned.replace(/<JSONPostProcessor(?![^>]*\bguiclass=)[^>]*>/g, (match) => {
    if (!match.includes('guiclass=')) {
      return match.replace('<JSONPostProcessor', '<JSONPostProcessor guiclass="JSONPostProcessorGui" testclass="JSONPostProcessor"');
    }
    return match;
  });

  // 10. Fix unescaped ampersands in URLs or XML attributes
  cleaned = cleaned.replace(/&(?!(amp|lt|gt|quot|apos|#\d+|#x[0-9a-fA-F]+);)/g, '&amp;');

  // 11. Ensure proper closing tags if file was truncated
  const majorTags = ['TestPlan', 'ThreadGroup', 'HTTPSamplerProxy', 'HeaderManager', 'ResultCollector', 'TransactionController'];
  majorTags.forEach((tagName) => {
    // Only match opening tags that are NOT self-closing (do not end with '/>')
    const openRegex = new RegExp(`<${tagName}\\b(?![^>]*\\/>)[^>]*>`, 'g');
    const closeRegex = new RegExp(`</${tagName}>`, 'g');
    const opens = (cleaned.match(openRegex) || []).length;
    const closes = (cleaned.match(closeRegex) || []).length;
    if (opens > closes) {
      for (let i = 0; i < (opens - closes); i++) {
        cleaned += `\n</${tagName}>`;
      }
    }
  });

  // Specifically ensure closing non-self-closing hashTrees match
  const countOpenHashTree = (cleaned.match(/<hashTree\b(?![^>]*\/>)[^>]*>/g) || []).length;
  const countCloseHashTree = (cleaned.match(/<\/hashTree>/g) || []).length;
  if (countOpenHashTree > countCloseHashTree) {
    for (let i = 0; i < (countOpenHashTree - countCloseHashTree); i++) {
      cleaned += '\n  </hashTree>';
    }
  }

  if (!cleaned.includes('</jmeterTestPlan>')) {
    cleaned += '\n</jmeterTestPlan>';
  }

  // 12. Ensure XML declaration is present at the very beginning
  if (!cleaned.startsWith('<?xml')) {
    cleaned = `<?xml version="1.0" encoding="UTF-8"?>\n${cleaned}`;
  }

  return cleaned;
}
